#!/usr/bin/env python3
"""gen325 (TODO.md P6 / forge-master-plan §18): project the capability ledger
into KB facts, so parrot0's answer about its own LIMITS is derived, not written.

Asked what it could not do, parrot0 said "I am parrot0." — and in Italian
("cosa non sai fare?") it listed what it CAN do, which is worse than a wall. It
had no notion of where its envelope ends, because the self-model derived only
from `module(name)`: a module either exists or it doesn't, and that says nothing
about how far it actually reaches.

The ledger already knows. `tests/benchmarks.json` declares each faculty's
maturity (ABSENT/SEED/TRANSFER/FIELD/HARDENED) and the WALL that blocks the next
level, and `make capability-report` verifies those claims against real gate
results. This projects that ledger into knowledge:

    capability(multi_file_editing, absent).
    capability_wall(multi_file_editing, "patch transaction + rollback").

so mod_self can answer from facts, and a faculty that regresses or is disabled
changes what parrot0 says about itself — with no code edit (§18: "disabling a
capability package removes the declared capacity").

The file is GENERATED. Editing kb/core/capabilities.p0 by hand would re-create
exactly the drift gen317 abolished for brain_version.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "tests" / "benchmarks.json"
LEDGER = ROOT / "capabilities" / "manifest.json"
OUT = ROOT / "kb" / "core" / "capabilities.p0"

HEADER = """% GENERATED by tests/capability_facts.py — do not edit by hand.
%
% gen325 (forge plan §18): parrot0's self-model must know where its envelope
% ENDS, not only which modules exist. These facts are projected from the
% capability ledger (tests/benchmarks.json, verified by `make capability-report`
% against real gate results), so "what can't you do?" is answered from evidence
% rather than from a paragraph someone wrote about themselves.
%
%   capability(Id, Maturity)     absent | seed | transfer | field | hardened
%   capability_wall(Id, "…")     what blocks the next level
%
% A faculty that regresses is downgraded here by the report, and parrot0's answer
% shrinks with it. That is the point: a self-description that cannot shrink is a
% brochure.
"""


def main() -> int:
    caps = json.loads(MANIFEST.read_text())["capabilities"]

    # If the generated ledger is present, prefer its VERIFIED maturity — a claim
    # that a gate contradicted must not be repeated as knowledge.
    verified: dict[str, str] = {}
    if LEDGER.is_file():
        try:
            for row in json.loads(LEDGER.read_text()).get("capabilities", []):
                if "id" in row and "maturity" in row:
                    verified[row["id"]] = str(row["maturity"])
        except (ValueError, KeyError):
            pass

    lines = [HEADER]
    for c in caps:
        cid = c["id"]
        maturity = verified.get(cid, c["maturity"]).lower()
        lines.append(f'capability({cid}, {maturity}).')
        wall = (c.get("wall") or "").strip()
        if wall:
            lines.append(f'capability_wall({cid}, "{wall}").')
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"capability-facts: wrote {OUT.relative_to(ROOT)} "
          f"({len(caps)} faculties, {len(verified)} verified from the ledger)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
