% parrot0 lexical knowledge - curated closed-class/function words.
% Loaded as base knowledge by brain_create before the optional world/session
% layers, so filters can consult the KB without persisting these facts.
% Predicate exported: stopword/1.

% English function words and high-frequency conversational operators.
stopword(the).
stopword(a).
stopword(an).
stopword(is).
stopword(are).
stopword(was).
stopword(were).
stopword(of).
stopword(to).
stopword(in).
stopword(on).
stopword(at).
stopword(and).
stopword(or).
stopword(for).
stopword(with).
stopword(that).
stopword(this).
stopword(it).
stopword(its).
stopword(as).
stopword(by).
stopword(be).
stopword(been).
stopword(being).
stopword(has).
stopword(have).
stopword(had).
stopword(do).
stopword(does).
stopword(did).
stopword(from).
stopword(but).
stopword(not).
stopword(no).
stopword(yes).
stopword(than).
stopword(then).
stopword(so).
stopword(if).
stopword(into).
stopword(out).
stopword(up).
stopword(down).
stopword(over).
stopword(under).
stopword(what).
stopword(which).
stopword(who).
stopword(whom).
stopword(whose).
stopword(when).
stopword(where).
stopword(why).
stopword(how).
stopword(there).
stopword(here).
stopword(their).
stopword(they).
stopword(them).
stopword(he).
stopword(she).
stopword(his).
stopword(her).
stopword(you).
stopword(your).
stopword(we).
stopword(our).
stopword(us).
stopword(i).
stopword(my).
stopword(me).
stopword(him).
stopword(will).
stopword(would).
stopword(can).
stopword(could).
stopword(should).
stopword(shall).
stopword(may).
stopword(might).
stopword(must).
stopword(also).
stopword(more).
stopword(most).
stopword(some).
stopword(any).
stopword(all).
stopword(each).
stopword(other).
stopword(such).
stopword(about).
stopword(after).
stopword(before).
stopword(between).
stopword(while).
stopword(because).
stopword(dont).
stopword(cant).
stopword(youre).
stopword(youve).
stopword(thats).

% Italian function words used by the bilingual probe and chat fallback.
stopword(il).
stopword(lo).
stopword(la).
stopword(gli).
stopword(le).
stopword(un).
stopword(uno).
stopword(una).
stopword(e).
stopword(ed).
stopword(o).
stopword(oppure).
stopword(ma).
stopword(non).
stopword(si).
stopword(è).
stopword(sono).
stopword(sei).
stopword(siamo).
stopword(siete).
stopword(ho).
stopword(hai).
stopword(ha).
stopword(abbiamo).
stopword(avete).
stopword(hanno).
stopword(mi).
stopword(ti).
stopword(ci).
stopword(vi).
stopword(mio).
stopword(mia).
stopword(miei).
stopword(mie).
stopword(tuo).
stopword(tua).
stopword(tuoi).
stopword(tue).
stopword(nostro).
stopword(nostra).
stopword(vostro).
stopword(vostra).
stopword(che).
stopword(chi).
stopword(cosa).
stopword(dove).
stopword(quando).
stopword(perche).
stopword(perché).
stopword(come).
stopword(quale).
stopword(quali).
stopword(questo).
stopword(questa).
stopword(quello).
stopword(quella).
stopword(qui).
stopword(li).
stopword(lì).
stopword(di).
stopword(da).
stopword(su).
stopword(per).
stopword(con).
stopword(tra).
stopword(fra).
stopword(stai).
stopword(parli).
stopword(basta).
stopword(dispiace).

% Italian conversational content words observed in chat-sim transcripts.
% These are NOT function words — they are common Italian filler/noun/verb forms
% that the fallback word-reflecting path would otherwise catalogue as unknown.
% Adding them as stopwords is the honest move: the system DOES see them but
% cannot reason about them; claiming "I don't know about X" for every one
% is the catalogue-of-ignorance anti-pattern.
stopword(niente).
stopword(nessun).
stopword(tranquillo).
stopword(confusione).
stopword(battuta).
stopword(essere).
stopword(imparando).
stopword(italiano).
stopword(inglese).
stopword(semplice).
stopword(spiegare).
stopword(parole).
stopword(complicate).
stopword(casino).
stopword(faccio).
stopword(pronto).
stopword(chiacchierare).
stopword(invertito).
stopword(ruoli).
stopword(solito).
stopword(aiuto).
stopword(domande).
stopword(paura).
stopword(chiedimi).
stopword(volentieri).
stopword(intendevo).
stopword(bravo).
stopword(significa).
stopword(provo).
stopword(tentativo).
stopword(inverso).
stopword(scherzo).
stopword(capito).
stopword(vuole).
stopword(usando).
stopword(parlo).
stopword(proviamo).
stopword(chiaro).
stopword(facile).
stopword(aiutarti).
stopword(aiutarmi).
stopword(spiegarti).
stopword(piacere).
stopword(volentieri).
stopword(nessuno).
stopword(funziona).
stopword(ancora).
stopword(parliamo).
stopword(devi).
stopword(vuoi).
stopword(vuol).
stopword(intendi).
stopword(formaggio).
stopword(piccolo).
stopword(pappagallo).
stopword(volta).
stopword(rotto).
stopword(cambiamento).
stopword(chiacchiere).

% English conversational fillers and content words observed in chat-sim
% transcripts. These are common English words the fallback word-reflecting
% path would otherwise catalogue ("Hmm, I don't know about X yet"). Adding
% them as stopwords is honest: the system does see them but cannot reason
% about them; claiming ignorance of each one is the catalogue-of-ignorance.
stopword(nothing).
stopword(enough).
stopword(purpose).
stopword(figure).
stopword(totally).
stopword(vibes).
stopword(vibin).
stopword(bored).
stopword(stuff).
stopword(stuck).
stopword(learn).
stopword(fair).
stopword(relax).
stopword(wanna).
stopword(gonna).
stopword(honey).
stopword(sweetie).
stopword(sweety).
stopword(babes).
stopword(indecisive).
stopword(weird).
stopword(weirdo).
stopword(bro).
stopword(dude).
stopword(omg).
stopword(seriously).
stopword(literally).
stopword(basically).
stopword(anyway).
stopword(anyways).
stopword(alright).
stopword(wow).
stopword(yep).
stopword(nope).
stopword(yeah).
stopword(nah).
stopword(okay).
stopword(okkk).
stopword(alrighty).
stopword(guess).
stopword(maybe).
stopword(kinda).
stopword(sorta).
stopword(something).
stopword(someone).
stopword(everyone).
stopword(everything).
stopword(anyone).
stopword(anything).
stopword(always).
stopword(never).
stopword(really).
stopword(actually).
stopword(already).
stopword(especially).
stopword(exactly).
stopword(definitely).
stopword(absolutely).
stopword(probably).
stopword(maybe).
stopword(perhaps).
stopword(sometimes).
stopword(usually).
stopword(often).
stopword(again).
