% parrot0 lexical knowledge - curated closed-class/function words.
% Loaded as base knowledge by brain_create before the optional world/session
% layers, so filters can consult the KB without persisting these facts.
% Predicate exported: stopword/1.

% English function words and high-frequency conversational operators.
stopword(the).
stopword(a).
stopword(an).
stopword(is).
stopword(are).
stopword(was).
stopword(were).
stopword(of).
stopword(to).
stopword(in).
stopword(on).
stopword(at).
stopword(and).
stopword(or).
stopword(for).
stopword(with).
stopword(that).
stopword(this).
stopword(it).
stopword(its).
stopword(as).
stopword(by).
stopword(be).
stopword(been).
stopword(being).
stopword(has).
stopword(have).
stopword(had).
stopword(do).
stopword(does).
stopword(did).
stopword(from).
stopword(but).
stopword(not).
stopword(no).
stopword(yes).
stopword(than).
stopword(then).
stopword(so).
stopword(if).
stopword(into).
stopword(out).
stopword(up).
stopword(down).
stopword(over).
stopword(under).
stopword(what).
stopword(which).
stopword(who).
stopword(whom).
stopword(whose).
stopword(when).
stopword(where).
stopword(why).
stopword(how).
stopword(there).
stopword(here).
stopword(their).
stopword(they).
stopword(them).
stopword(he).
stopword(she).
stopword(his).
stopword(her).
stopword(you).
stopword(your).
stopword(we).
stopword(our).
stopword(us).
stopword(i).
stopword(my).
stopword(me).
stopword(him).
stopword(will).
stopword(would).
stopword(can).
stopword(could).
stopword(should).
stopword(shall).
stopword(may).
stopword(might).
stopword(must).
stopword(also).
stopword(more).
stopword(most).
stopword(some).
stopword(any).
stopword(all).
stopword(each).
stopword(other).
stopword(such).
stopword(about).
stopword(after).
stopword(before).
stopword(between).
stopword(while).
stopword(because).
stopword(dont).
stopword(cant).
stopword(youre).
stopword(youve).
stopword(thats).

% Italian function words used by the bilingual probe and chat fallback.
stopword(il).
stopword(lo).
stopword(la).
stopword(gli).
stopword(le).
stopword(un).
stopword(uno).
stopword(una).
stopword(e).
stopword(ed).
stopword(o).
stopword(oppure).
stopword(ma).
stopword(non).
stopword(si).
stopword(è).
stopword(sono).
stopword(sei).
stopword(siamo).
stopword(siete).
stopword(ho).
stopword(hai).
stopword(ha).
stopword(abbiamo).
stopword(avete).
stopword(hanno).
stopword(mi).
stopword(ti).
stopword(ci).
stopword(vi).
stopword(mio).
stopword(mia).
stopword(miei).
stopword(mie).
stopword(tuo).
stopword(tua).
stopword(tuoi).
stopword(tue).
stopword(nostro).
stopword(nostra).
stopword(vostro).
stopword(vostra).
stopword(che).
stopword(chi).
stopword(cosa).
stopword(dove).
stopword(quando).
stopword(perche).
stopword(perché).
stopword(come).
stopword(quale).
stopword(quali).
stopword(questo).
stopword(questa).
stopword(quello).
stopword(quella).
stopword(qui).
stopword(li).
stopword(lì).
stopword(di).
stopword(da).
stopword(su).
stopword(per).
stopword(con).
stopword(tra).
stopword(fra).
stopword(stai).
stopword(parli).
stopword(basta).
stopword(dispiace).
