#!/usr/bin/env python3
"""Generate finite, inspectable game substrates for the Parrot0 KB.

The generated clauses are intentionally domain knowledge, not filler:

* chess board topology plus state-dependent Horn transitions for kings,
  knights, and pawns;
* the 19x19 Go graph;
* Sudoku cells, units, peers, and possible digits;
* a standard 52-card deck with useful pairwise relations.

Run from any directory. Output is deterministic and is committed together with
this generator so every large knowledge file remains auditable/reproducible.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "kb" / "experts" / "games"
FILES = "abcdefgh"
SUITS = ("clubs", "diamonds", "hearts", "spades")
RANKS = (
    ("two", 2), ("three", 3), ("four", 4), ("five", 5),
    ("six", 6), ("seven", 7), ("eight", 8), ("nine", 9),
    ("ten", 10), ("jack", 11), ("queen", 12), ("king", 13),
    ("ace", 14),
)


def write_generated(name: str, title: str, facts: list[str], rules: list[str]) -> None:
    lines = [
        f"% GENERATED by scripts/generate_game_kb.py — {title}",
        "% Do not hand-edit: change the generator and rerun it.",
        f"% direct facts: {len(facts)} | Horn rules: {len(rules)}",
        "",
        "% --- facts ---",
        *facts,
        "",
        "% --- rules ---",
        *rules,
        "",
    ]
    (OUT / name).write_text("\n".join(lines), encoding="utf-8")
    print(f"{name}: {len(facts)} facts, {len(rules)} rules")


def square(file_index: int, rank: int) -> str:
    return f"{FILES[file_index]}{rank}"


def generate_chess() -> None:
    facts: list[str] = []
    rules: list[str] = []
    for file_name in FILES:
        facts.append(f"chess_file({file_name}).")
    for rank in range(1, 9):
        facts.append(f"chess_rank({rank}).")
    for file_index, file_name in enumerate(FILES):
        for rank in range(1, 9):
            color = "dark" if (file_index + rank) % 2 == 0 else "light"
            facts.append(
                f"chess_square({square(file_index, rank)}, {file_name}, {rank}, {color})."
            )
    facts.extend((
        "chess_slider(rook).", "chess_slider(bishop).", "chess_slider(queen).",
        "chess_leaper(king).", "chess_leaper(knight).",
        "chess_pawn_direction(white, north).",
        "chess_pawn_direction(black, south).",
    ))

    for file_index in range(8):
        for rank in range(1, 9):
            origin = square(file_index, rank)
            rook_targets: set[str] = set()
            bishop_targets: set[str] = set()
            for other_file in range(8):
                if other_file != file_index:
                    rook_targets.add(square(other_file, rank))
            for other_rank in range(1, 9):
                if other_rank != rank:
                    rook_targets.add(square(file_index, other_rank))
            for df, dr in ((1, 1), (1, -1), (-1, 1), (-1, -1)):
                nf, nr = file_index + df, rank + dr
                while 0 <= nf < 8 and 1 <= nr <= 8:
                    bishop_targets.add(square(nf, nr))
                    nf += df
                    nr += dr
            for target in sorted(rook_targets):
                facts.append(f"chess_empty_move(rook, {origin}, {target}).")
            for target in sorted(bishop_targets):
                facts.append(f"chess_empty_move(bishop, {origin}, {target}).")
            for target in sorted(rook_targets | bishop_targets):
                facts.append(f"chess_empty_move(queen, {origin}, {target}).")

            for df in (-1, 0, 1):
                for dr in (-1, 0, 1):
                    if df == 0 and dr == 0:
                        continue
                    nf, nr = file_index + df, rank + dr
                    if 0 <= nf < 8 and 1 <= nr <= 8:
                        target = square(nf, nr)
                        rules.append(
                            f"chess_king_option($State, $Side, {origin}, {target}) :- "
                            f"chess_piece_at($State, piece($Side, king), {origin}), "
                            f"chess_destination_open($State, $Side, {target}), "
                            f"naf(chess_attacked_by_opponent($State, $Side, {target}))."
                        )
            for df, dr in (
                (-2, -1), (-2, 1), (-1, -2), (-1, 2),
                (1, -2), (1, 2), (2, -1), (2, 1),
            ):
                nf, nr = file_index + df, rank + dr
                if 0 <= nf < 8 and 1 <= nr <= 8:
                    target = square(nf, nr)
                    rules.append(
                        f"chess_knight_option($State, $Side, {origin}, {target}) :- "
                        f"chess_piece_at($State, piece($Side, knight), {origin}), "
                        f"chess_destination_open($State, $Side, {target})."
                    )

    for side, direction, start_rank in (("white", 1, 2), ("black", -1, 7)):
        for file_index in range(8):
            for rank in range(2, 8):
                origin = square(file_index, rank)
                target_rank = rank + direction
                if 1 <= target_rank <= 8:
                    target = square(file_index, target_rank)
                    rules.append(
                        f"chess_pawn_advance($State, {side}, {origin}, {target}) :- "
                        f"chess_piece_at($State, piece({side}, pawn), {origin}), "
                        f"chess_empty($State, {target})."
                    )
                    for df in (-1, 1):
                        nf = file_index + df
                        if 0 <= nf < 8:
                            capture = square(nf, target_rank)
                            rules.append(
                                f"chess_pawn_capture($State, {side}, {origin}, {capture}) :- "
                                f"chess_piece_at($State, piece({side}, pawn), {origin}), "
                                f"chess_enemy_at($State, {side}, {capture})."
                            )
            origin = square(file_index, start_rank)
            middle = square(file_index, start_rank + direction)
            target = square(file_index, start_rank + 2 * direction)
            rules.append(
                f"chess_pawn_double($State, {side}, {origin}, {target}) :- "
                f"chess_piece_at($State, piece({side}, pawn), {origin}), "
                f"chess_empty($State, {middle}), chess_empty($State, {target})."
            )

    write_generated(
        "chess_board.p0", "complete empty-board topology and local move procedures",
        facts, rules,
    )


def go_point(x: int, y: int) -> str:
    return f"go_{x:02d}_{y:02d}"


def generate_go() -> None:
    facts: list[str] = []
    for x in range(1, 20):
        for y in range(1, 20):
            point = go_point(x, y)
            facts.append(f"go_intersection({point}, {x}, {y}).")
            if x in (1, 19) or y in (1, 19):
                facts.append(f"go_edge_intersection({point}).")
            if x in (1, 19) and y in (1, 19):
                facts.append(f"go_corner_intersection({point}).")
            if x in (4, 10, 16) and y in (4, 10, 16):
                facts.append(f"go_star_point({point}).")
            for dx, dy in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                nx, ny = x + dx, y + dy
                if 1 <= nx <= 19 and 1 <= ny <= 19:
                    facts.append(f"go_neighbor({point}, {go_point(nx, ny)}).")
    rules = [
        "go_liberty($State, $Point, $Neighbor) :- go_stone_at($State, $Color, $Point), go_neighbor($Point, $Neighbor), go_empty($State, $Neighbor).",
        "go_connected($State, $A, $B) :- go_stone_at($State, $Color, $A), go_stone_at($State, $Color, $B), go_neighbor($A, $B).",
        "go_connected($State, $A, $C) :- go_connected($State, $A, $B), go_connected($State, $B, $C).",
        "go_in_atari($State, $Point) :- go_liberty($State, $Point, $Only), naf(go_second_liberty($State, $Point, $Only)).",
        "go_second_liberty($State, $Point, $Known) :- go_liberty($State, $Point, $Other), dif($Known, $Other).",
    ]
    write_generated("go_board.p0", "19x19 board graph and group primitives", facts, rules)


def sudoku_cell(row: int, col: int) -> str:
    return f"r{row}c{col}"


def generate_sudoku() -> None:
    facts: list[str] = []
    cells: dict[tuple[int, int], str] = {}
    for row in range(1, 10):
        for col in range(1, 10):
            cell = sudoku_cell(row, col)
            box = ((row - 1) // 3) * 3 + ((col - 1) // 3) + 1
            cells[(row, col)] = cell
            facts.append(f"sudoku_cell({cell}, {row}, {col}, {box}).")
            facts.append(f"sudoku_unit_member(row_{row}, {cell}).")
            facts.append(f"sudoku_unit_member(column_{col}, {cell}).")
            facts.append(f"sudoku_unit_member(box_{box}, {cell}).")
            for digit in range(1, 10):
                facts.append(f"sudoku_possible_digit({cell}, {digit}).")
    for (row, col), cell in cells.items():
        box = ((row - 1) // 3, (col - 1) // 3)
        for (other_row, other_col), other in cells.items():
            if other == cell:
                continue
            other_box = ((other_row - 1) // 3, (other_col - 1) // 3)
            if row == other_row or col == other_col or box == other_box:
                facts.append(f"sudoku_peer({cell}, {other}).")
    rules = [
        "sudoku_conflict($Cell, $Peer, $Digit) :- sudoku_peer($Cell, $Peer), sudoku_value($Cell, $Digit), sudoku_value($Peer, $Digit).",
        "sudoku_blocked($Cell, $Digit) :- sudoku_peer($Cell, $Peer), sudoku_value($Peer, $Digit).",
        "sudoku_live_candidate($Cell, $Digit) :- sudoku_possible_digit($Cell, $Digit), naf(sudoku_blocked($Cell, $Digit)).",
        "sudoku_forced($Cell, $Digit) :- sudoku_live_candidate($Cell, $Digit), naf(sudoku_other_candidate($Cell, $Digit)).",
        "sudoku_other_candidate($Cell, $Digit) :- sudoku_live_candidate($Cell, $Other), dif($Digit, $Other).",
    ]
    write_generated("sudoku_grid.p0", "9x9 cells, units, peers and candidate substrate", facts, rules)


def generate_cards() -> None:
    facts: list[str] = []
    cards: list[tuple[str, str, str, int, str]] = []
    for suit in SUITS:
        color = "red" if suit in ("diamonds", "hearts") else "black"
        for rank, value in RANKS:
            card = f"{rank}_of_{suit}"
            cards.append((card, rank, suit, value, color))
            facts.append(f"playing_card({card}, {rank}, {suit}, {value}).")
            facts.append(f"card_color({card}, {color}).")
    for card_a, rank_a, suit_a, value_a, color_a in cards:
        for card_b, rank_b, suit_b, value_b, color_b in cards:
            if card_a == card_b:
                continue
            if suit_a == suit_b:
                facts.append(f"same_suit_card({card_a}, {card_b}).")
            if rank_a == rank_b:
                facts.append(f"same_rank_card({card_a}, {card_b}).")
            if value_a > value_b:
                facts.append(f"higher_rank_card({card_a}, {card_b}).")
            if color_a != color_b:
                facts.append(f"opposite_color_card({card_a}, {card_b}).")
    rules = [
        "card_rank_value($Card, $Value) :- playing_card($Card, $Rank, $Suit, $Value).",
        "blackjack_value($Card, 10) :- playing_card($Card, jack, $Suit, $RankValue).",
        "blackjack_value($Card, 10) :- playing_card($Card, queen, $Suit, $RankValue).",
        "blackjack_value($Card, 10) :- playing_card($Card, king, $Suit, $RankValue).",
        "blackjack_value($Card, 11) :- playing_card($Card, ace, $Suit, $RankValue).",
        "blackjack_value($Card, $Value) :- playing_card($Card, $Rank, $Suit, $Value), le($Value, 10).",
        "poker_suited_pair($A, $B) :- same_suit_card($A, $B).",
        "poker_rank_pair($A, $B) :- same_rank_card($A, $B).",
        "solitaire_alternating_pair($Higher, $Lower) :- opposite_color_card($Higher, $Lower), higher_rank_card($Higher, $Lower).",
    ]
    write_generated("standard_cards.p0", "standard deck and pairwise card relations", facts, rules)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    generate_chess()
    generate_go()
    generate_sudoku()
    generate_cards()


if __name__ == "__main__":
    main()
