#!/usr/bin/env python3
"""Generate a curated, cross-cultural humanities layer for Parrot0."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def quote(text: str) -> str:
    # answer_frame owns terminal sentence punctuation; storing it here would
    # produce a doubled full stop when a summary is spoken.
    text = text.rstrip()
    if text.endswith("."):
        text = text[:-1]
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(path: str, title: str, facts: list[str], rules: list[str]) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    body = [
        f"% GENERATED by scripts/generate_humanities_kb.py — {title}",
        "% Curated source table is below in the generator; regenerate after edits.",
        f"% direct facts: {len(facts)} | Horn rules: {len(rules)}",
        "",
        *facts,
        "",
        "% --- reusable inferences ---",
        *rules,
        "",
    ]
    target.write_text("\n".join(body), encoding="utf-8")
    print(f"{path}: {len(facts)} facts, {len(rules)} rules")


def literature() -> None:
    rows = [
        ("epic_of_gilgamesh", "anonymous_mesopotamian_scribes", "mesopotamian", "epic", "ancient", "mortality", "kingship", "An ancient Mesopotamian epic in which Gilgamesh confronts friendship, loss, kingship and human mortality."),
        ("iliad", "homer", "ancient_greek", "epic", "archaic", "war", "honor", "An epic centered on the anger of Achilles and the human cost of honor, war and loss at Troy."),
        ("odyssey", "homer", "ancient_greek", "epic", "archaic", "homecoming", "identity", "An epic of Odysseus returning home through trials involving hospitality, memory, disguise and loyalty."),
        ("mahabharata", "vyasa_tradition", "sanskrit", "epic", "ancient", "dharma", "kinship", "A vast Sanskrit epic about a dynastic conflict that examines duty, kinship, violence and moral ambiguity."),
        ("ramayana", "valmiki_tradition", "sanskrit", "epic", "ancient", "duty", "exile", "A Sanskrit epic following Rama, Sita and their allies through exile, abduction, war and debates about righteous conduct."),
        ("shijing", "anonymous_zhou_poets", "classical_chinese", "poetry_collection", "ancient", "ritual", "daily_life", "The Classic of Poetry gathers early Chinese songs about ritual, labor, courtship, farming and political judgment."),
        ("tale_of_genji", "murasaki_shikibu", "japanese", "novel", "heian", "impermanence", "court_life", "A Heian court narrative of intimacy, status, aesthetics and impermanence, often called an early novel."),
        ("thousand_and_one_nights", "multiple_transmitters", "arabic_persian", "frame_tale", "medieval", "storytelling", "survival", "A layered collection in which Scheherazade's storytelling frames tales of travel, wit, wonder, danger and justice."),
        ("divine_comedy", "dante_alighieri", "italian", "narrative_poem", "medieval", "afterlife", "moral_order", "Dante's journey through Hell, Purgatory and Paradise joins theology, politics, ethics and poetic autobiography."),
        ("decameron", "giovanni_boccaccio", "italian", "story_cycle", "medieval", "fortune", "social_life", "One hundred tales told during a plague explore fortune, desire, intelligence, hypocrisy and social mobility."),
        ("don_quixote", "miguel_de_cervantes", "spanish", "novel", "early_modern", "imagination", "reality", "A novel about a reader who becomes a wandering knight, testing the boundaries between fiction, reality and social performance."),
        ("hamlet", "william_shakespeare", "english", "tragedy", "early_modern", "revenge", "uncertainty", "A tragedy in which Hamlet investigates his father's death while thought, performance, grief and revenge delay decisive action."),
        ("paradise_lost", "john_milton", "english", "epic", "early_modern", "freedom", "fall", "An English epic retelling the fall of Satan and humanity through questions of obedience, freedom, pride and responsibility."),
        ("dream_of_the_red_chamber", "cao_xueqin", "chinese", "novel", "qing", "family_decline", "desire", "A Qing novel tracing the fortunes of an elite household through love, ritual, material culture and social decline."),
        ("candide", "voltaire", "french", "satirical_novella", "enlightenment", "optimism", "suffering", "A philosophical satire whose disasters challenge easy optimism and end by valuing practical work."),
        ("faust", "johann_wolfgang_von_goethe", "german", "dramatic_poem", "romantic", "knowledge", "striving", "Goethe's Faust bargains for expanded experience in a drama about knowledge, desire, responsibility and restless striving."),
        ("pride_and_prejudice", "jane_austen", "english", "novel", "regency", "marriage", "judgment", "A novel of courtship and social judgment that examines class, property, first impressions and moral growth."),
        ("frankenstein", "mary_shelley", "english", "novel", "romantic", "creation", "responsibility", "A framed Gothic novel about scientific creation, abandonment and the responsibilities linking maker, creature and society."),
        ("dead_souls", "nikolai_gogol", "russian", "satirical_novel", "nineteenth_century", "bureaucracy", "status", "A satirical journey through provincial Russia built around a scheme to buy the legal identities of deceased serfs."),
        ("madame_bovary", "gustave_flaubert", "french", "novel", "realist", "desire", "consumerism", "A realist novel about Emma Bovary's dissatisfaction, romantic fantasies, debts and constrained provincial life."),
        ("moby_dick", "herman_melville", "american", "novel", "nineteenth_century", "obsession", "nature", "A many-voiced maritime novel in which Ahab's pursuit of a whale becomes an inquiry into obsession, labor, knowledge and nature."),
        ("leaves_of_grass", "walt_whitman", "american", "poetry_collection", "nineteenth_century", "democracy", "body", "A continually revised poetry collection celebrating the body, labor, plurality, landscape and democratic possibility."),
        ("crime_and_punishment", "fyodor_dostoevsky", "russian", "novel", "nineteenth_century", "guilt", "redemption", "A psychological novel following murder, rationalization, guilt, poverty and the possibility of moral transformation."),
        ("war_and_peace", "leo_tolstoy", "russian", "novel", "nineteenth_century", "history", "family", "A panoramic novel interweaving families and Napoleonic war while questioning heroic explanations of history."),
        ("middlemarch", "george_eliot", "english", "novel", "victorian", "reform", "interdependence", "A multi-plot provincial novel about marriage, vocation, reform and the unintended effects of interdependent lives."),
        ("the_brothers_karamazov", "fyodor_dostoevsky", "russian", "novel", "nineteenth_century", "faith", "responsibility", "A family and courtroom novel that stages conflicts over faith, freedom, patricide and shared moral responsibility."),
        ("the_trial", "franz_kafka", "german_language", "novel", "modernist", "bureaucracy", "guilt", "An unfinished novel in which Josef K faces an opaque legal process, turning administration into existential uncertainty."),
        ("things_fall_apart", "chinua_achebe", "nigerian", "novel", "postcolonial", "colonialism", "social_change", "A novel about Okonkwo and an Igbo community confronting internal tensions and the disruptions of British colonial rule."),
        ("invisible_man", "ralph_ellison", "african_american", "novel", "modern", "race", "identity", "A first-person novel tracing how institutions and ideologies render a Black narrator socially invisible while he seeks self-definition."),
        ("the_stranger", "albert_camus", "francophone_algerian", "novel", "modern", "absurdity", "alienation", "A spare novel whose crime and trial expose alienation, social expectation and Camus's problem of the absurd."),
        ("garden_of_forking_paths", "jorge_luis_borges", "argentine", "short_story", "modern", "time", "interpretation", "A labyrinthine story linking espionage, books and a model of time in which possibilities branch rather than disappear."),
        ("one_hundred_years_of_solitude", "gabriel_garcia_marquez", "colombian", "novel", "latin_american_boom", "memory", "history", "A multigenerational chronicle of Macondo where political violence, family repetition and wonder reshape historical memory."),
        ("season_of_migration_to_the_north", "tayeb_salih", "sudanese", "novel", "postcolonial", "migration", "colonial_encounter", "A novel of return and doubled lives that reverses colonial travel narratives between Sudan and Britain."),
        ("beloved", "toni_morrison", "african_american", "novel", "contemporary", "slavery", "memory", "A haunted novel about a family living with the embodied memory and continuing violence of American slavery."),
    ]
    facts = [
        "expert(world_literature).",
        "expert_domain(world_literature, literature).",
        f"expert_description(world_literature, {quote('works, traditions, forms and themes across world literature')}).",
    ]
    for work, author, tradition, form, period, theme_a, theme_b, desc in rows:
        facts.extend((
            f"literary_work({work}, {author}, {tradition}, {form}).",
            f"author_of({author}, {work}).",
            f"literary_period({work}, {period}).",
            f"literary_theme({work}, {theme_a}).",
            f"literary_theme({work}, {theme_b}).",
            f"humanities_topic({work}).",
            f"means({work}, {quote(desc)}).",
            f"literary_author({author}).",
        ))
    rules = [
        "literature_topic($Work) :- literary_work($Work, $Author, $Tradition, $Form).",
        "work_by($Work, $Author) :- author_of($Author, $Work).",
        "same_literary_tradition($A, $B) :- literary_work($A, $AuthorA, $Tradition, $FormA), literary_work($B, $AuthorB, $Tradition, $FormB), dif($A, $B).",
        "shares_literary_theme($A, $B, $Theme) :- literary_theme($A, $Theme), literary_theme($B, $Theme), dif($A, $B).",
        "epic_work($Work) :- literary_work($Work, $Author, $Tradition, epic).",
        "novel_work($Work) :- literary_work($Work, $Author, $Tradition, novel).",
        "translated_literature($Work) :- literary_work($Work, $Author, $Tradition, $Form), dif($Tradition, english).",
        "author_in_tradition($Author, $Tradition) :- literary_work($Work, $Author, $Tradition, $Form).",
    ]
    emit("kb/experts/literature/world_literature.p0", "world literature", facts, rules)


def philosophy() -> None:
    rows = [
        ("confucius", "confucian", "analects", "ren", "ancient_china", "Confucius linked ethical cultivation, humane conduct, ritual practice and responsible social roles."),
        ("laozi", "daoist", "daodejing", "wu_wei", "ancient_china", "The Laozi presents a politics and ethics of non-forcing, simplicity and responsiveness to the Dao."),
        ("gautama_buddha", "buddhist", "early_discourses", "dependent_origination", "ancient_india", "Buddhist teaching analyzes suffering, impermanence and dependent arising while proposing an ethical path of liberation."),
        ("mahavira", "jain", "jain_agamas", "ahimsa", "ancient_india", "Jain philosophy emphasizes nonviolence, disciplined liberation and the many-sided character of truth."),
        ("socrates", "socratic", "socratic_dialogues", "examined_life", "ancient_greece", "Socrates used questioning to test claims about virtue, knowledge and how one should live."),
        ("plato", "platonist", "republic", "forms", "ancient_greece", "Plato connected metaphysics, knowledge, ethics and political order through dialogues and the theory of forms."),
        ("aristotle", "aristotelian", "nicomachean_ethics", "virtue", "ancient_greece", "Aristotle treated logic, nature, ethics and politics through causal explanation and the cultivation of practical virtue."),
        ("epicurus", "epicurean", "letter_to_menoeceus", "ataraxia", "hellenistic", "Epicurus argued that prudent pleasure, friendship and freedom from needless fear support tranquility."),
        ("zeno_of_citium", "stoic", "republic_of_zeno", "living_according_to_nature", "hellenistic", "Early Stoicism made virtue and rational alignment with nature central to a flourishing life."),
        ("augustine", "christian_platonist", "confessions", "interiority", "late_antiquity", "Augustine joined Christian theology with Platonist themes in accounts of time, memory, will and grace."),
        ("ibn_sina", "islamic_peripatetic", "book_of_healing", "necessary_existent", "medieval_islamic", "Ibn Sina developed influential accounts of logic, soul, causation and the necessary existent."),
        ("al_ghazali", "islamic_theology", "incoherence_of_the_philosophers", "occasionalism", "medieval_islamic", "Al-Ghazali examined the limits of philosophical demonstration and defended a theologically grounded account of causation."),
        ("ibn_rushd", "andalusian_aristotelian", "incoherence_of_the_incoherence", "philosophy_and_revelation", "medieval_islamic", "Ibn Rushd defended Aristotelian philosophy and argued that disciplined reasoning can coexist with revelation."),
        ("maimonides", "jewish_aristotelian", "guide_for_the_perplexed", "negative_theology", "medieval_jewish", "Maimonides joined Jewish law and Aristotelian inquiry while stressing the limits of positive claims about God."),
        ("thomas_aquinas", "scholastic", "summa_theologiae", "natural_law", "medieval_christian", "Aquinas synthesized Aristotelian philosophy and Christian theology in accounts of being, law, virtue and knowledge."),
        ("rene_descartes", "rationalist", "meditations", "methodic_doubt", "early_modern", "Descartes used systematic doubt to seek secure foundations for knowledge and distinguish mind from extended matter."),
        ("baruch_spinoza", "rationalist", "ethics", "substance_monism", "early_modern", "Spinoza described mind and body as aspects of one substance and freedom as understanding necessity."),
        ("john_locke", "empiricist", "essay_concerning_human_understanding", "experience", "early_modern", "Locke grounded ideas in experience and linked political authority to consent and natural rights."),
        ("david_hume", "empiricist", "treatise_of_human_nature", "habit", "enlightenment", "Hume explained causal expectation, identity and much moral judgment through custom, sentiment and limited experience."),
        ("immanuel_kant", "critical_philosophy", "critique_of_pure_reason", "transcendental_idealism", "enlightenment", "Kant argued that experience is structured by forms and concepts while ethics rests on autonomous practical reason."),
        ("g_w_f_hegel", "german_idealist", "phenomenology_of_spirit", "dialectic", "nineteenth_century", "Hegel analyzed historical forms of consciousness through conflict, recognition and institutional development."),
        ("soren_kierkegaard", "existential", "either_or", "subjective_commitment", "nineteenth_century", "Kierkegaard explored anxiety, choice, faith and the irreducibly personal character of commitment."),
        ("karl_marx", "historical_materialist", "capital", "class_struggle", "nineteenth_century", "Marx analyzed capitalism through labor, value, class relations, accumulation and historically changing material institutions."),
        ("friedrich_nietzsche", "genealogical", "on_the_genealogy_of_morality", "value_creation", "nineteenth_century", "Nietzsche traced moral values historically and criticized resentment, conformity and inherited metaphysical comforts."),
        ("william_james", "pragmatist", "pragmatism", "practical_consequences", "modern", "James assessed ideas through their experiential and practical consequences while defending pluralism."),
        ("edmund_husserl", "phenomenologist", "ideas", "intentionality", "modern", "Husserl investigated structures of experience and intentionality through disciplined first-person description."),
        ("ludwig_wittgenstein", "analytic", "philosophical_investigations", "language_games", "modern", "Wittgenstein treated meaning as use within practices and diagnosed philosophical confusion through attention to language."),
        ("simone_de_beauvoir", "existential_feminist", "the_second_sex", "situation", "modern", "Beauvoir analyzed gender as historically produced within unequal situations while defending freedom and reciprocity."),
        ("hannah_arendt", "political_thought", "the_human_condition", "plurality", "modern", "Arendt distinguished labor, work and action and made plurality central to public freedom and political responsibility."),
        ("frantz_fanon", "anticolonial", "the_wretched_of_the_earth", "decolonization", "modern", "Fanon analyzed colonial violence, racialization, psychic injury and the contested making of postcolonial freedom."),
        ("john_rawls", "political_liberal", "a_theory_of_justice", "original_position", "contemporary", "Rawls used the original position to model fair principles for basic liberties and social distribution."),
        ("michel_foucault", "genealogical", "discipline_and_punish", "power_knowledge", "contemporary", "Foucault studied how institutions, expert knowledge and practices produce disciplined subjects and regimes of truth."),
        ("judith_butler", "queer_feminist", "gender_trouble", "performativity", "contemporary", "Butler argues that repeated social acts produce gendered identities while norms remain open to contestation."),
        ("kwame_anthony_appiah", "cosmopolitan", "cosmopolitanism", "conversation_across_difference", "contemporary", "Appiah defends ethical concern across borders joined with respectful disagreement and local attachments."),
    ]
    facts = [
        "expert(history_of_philosophy).",
        "expert_domain(history_of_philosophy, philosophy).",
        f"expert_description(history_of_philosophy, {quote('philosophers, schools, works and concepts across traditions')}).",
    ]
    for thinker, school, work, concept, period, desc in rows:
        facts.extend((
            f"philosopher({thinker}).",
            f"philosophical_school({thinker}, {school}).",
            f"philosophical_work({thinker}, {work}).",
            f"philosophical_concept({thinker}, {concept}).",
            f"philosophical_period({thinker}, {period}).",
            f"humanities_topic({thinker}).",
            f"means({thinker}, {quote(desc)}).",
        ))
    rules = [
        "thinker_in_school($Thinker, $School) :- philosophical_school($Thinker, $School).",
        "shares_philosophical_period($A, $B) :- philosophical_period($A, $Period), philosophical_period($B, $Period), dif($A, $B).",
        "shares_philosophical_school($A, $B) :- philosophical_school($A, $School), philosophical_school($B, $School), dif($A, $B).",
        "concept_by($Concept, $Thinker) :- philosophical_concept($Thinker, $Concept).",
        "work_by_philosopher($Work, $Thinker) :- philosophical_work($Thinker, $Work).",
        "ancient_philosopher($Thinker) :- philosophical_period($Thinker, ancient_greece).",
        "ancient_philosopher($Thinker) :- philosophical_period($Thinker, ancient_china).",
        "ancient_philosopher($Thinker) :- philosophical_period($Thinker, ancient_india).",
        "modern_philosopher($Thinker) :- philosophical_period($Thinker, modern).",
        "contemporary_philosopher($Thinker) :- philosophical_period($Thinker, contemporary).",
    ]
    emit("kb/experts/philosophy/history.p0", "history of philosophy", facts, rules)


def anthropology() -> None:
    thinkers = [
        ("franz_boas", "historical_particularism", "cultural_relativism", "Boas opposed racial determinism and emphasized historical context, field evidence and cultural variation."),
        ("bronislaw_malinowski", "functionalism", "participant_observation", "Malinowski made long-term fieldwork and attention to everyday institutions central to social anthropology."),
        ("margaret_mead", "culture_and_personality", "adolescence_and_culture", "Mead used comparative fieldwork to argue that development and gender expectations vary culturally."),
        ("ruth_benedict", "culture_and_personality", "patterns_of_culture", "Benedict examined how societies select and organize different ranges of human possibility."),
        ("marcel_mauss", "french_sociology", "gift_exchange", "Mauss showed that gifts can bind economy, law, morality, spirituality and political obligation."),
        ("claude_levi_strauss", "structuralism", "binary_structure", "Levi-Strauss analyzed kinship and myth through transformations among underlying relational structures."),
        ("e_e_evans_pritchard", "british_social_anthropology", "social_context_of_belief", "Evans-Pritchard interpreted institutions and explanations within coherent social and historical contexts."),
        ("victor_turner", "symbolic_anthropology", "liminality", "Turner studied ritual process, social drama, liminality and temporary forms of communitas."),
        ("clifford_geertz", "interpretive_anthropology", "thick_description", "Geertz treated culture as public webs of meaning interpreted through thick description."),
        ("mary_douglas", "symbolic_anthropology", "purity_and_danger", "Douglas linked classification, pollution and taboo to the maintenance and contestation of social order."),
        ("eric_wolf", "political_economy", "connected_histories", "Wolf placed local communities within colonialism, markets, labor systems and connected world histories."),
        ("sidney_mintz", "political_economy", "commodity_history", "Mintz connected sugar consumption to plantation slavery, industrial labor and changing taste."),
        ("pierre_bourdieu", "practice_theory", "habitus", "Bourdieu analyzed how embodied dispositions, fields and forms of capital reproduce and transform social life."),
        ("sherry_ortner", "practice_theory", "serious_games", "Ortner linked agency, power and cultural projects through historically situated practice."),
        ("lila_abu_lughod", "feminist_anthropology", "writing_against_culture", "Abu-Lughod critiques bounded pictures of culture and emphasizes situated lives, power and historical connection."),
        ("marilyn_strathern", "melanesian_anthropology", "dividual_personhood", "Strathern examined relations, exchange and personhood while challenging Western assumptions about individuals."),
        ("david_graeber", "anarchist_anthropology", "debt", "Graeber compared debt, value, bureaucracy and political imagination across long historical spans."),
        ("anna_tsing", "multispecies_anthropology", "friction", "Tsing studies global connection, ecological disturbance and collaboration across unequal human and nonhuman worlds."),
    ]
    concepts = [
        ("participant_observation", "fieldwork", "Learning through sustained participation, observation, conversation and reflection in a community while documenting one's position and limits."),
        ("cultural_relativism", "method", "Interpreting practices in their historical and cultural context without treating one's own conventions as the universal standard."),
        ("ethnocentrism", "bias", "Judging other ways of life primarily through the categories and values of one's own group."),
        ("gift_exchange", "exchange", "Transfers that create or negotiate relationships, obligations, status and moral claims beyond a spot market transaction."),
        ("rites_of_passage", "ritual", "Ceremonies marking changes of social status, often analyzed through separation, transition and incorporation."),
        ("liminality", "ritual", "A threshold condition in which an earlier status has been left but a new status is not yet fully established."),
        ("kinship", "social_organization", "Culturally organized relations of descent, marriage, care, residence, inheritance and belonging."),
        ("totemism", "classification", "Relations linking social groups, species, places or emblems within systems of identity and difference."),
        ("taboo", "norm", "A strongly marked prohibition whose force may be religious, moral, political, ecological or social."),
        ("potlatch", "ceremonial_exchange", "Ceremonial distributions among Indigenous peoples of the Northwest Coast that establish names, rights, rank and reciprocal obligations."),
        ("kula_ring", "ceremonial_exchange", "A regional exchange network in the Massim through which valued shell objects circulate alongside trade and political relationships."),
        ("ancestor_veneration", "religion", "Practices maintaining reciprocal moral and ritual relations between living communities and remembered ancestors."),
        ("oral_tradition", "knowledge_transmission", "Transmission of history, law, performance and practical knowledge through spoken, sung and enacted forms."),
        ("pastoralism", "subsistence", "Livelihood organized substantially around managed herds, mobility, land access and exchange with other communities."),
        ("horticulture", "subsistence", "Small-scale cultivation using hand tools, often combined with gathering, trade, hunting or animal keeping."),
        ("transhumance", "mobility", "Seasonal movement of herders and livestock between established grazing zones."),
        ("bridewealth", "marriage_exchange", "Transfers associated with marriage that can recognize relationships and obligations between families or descent groups."),
        ("dowry", "marriage_exchange", "Property transferred in connection with marriage, with meanings and control varying greatly by legal and social context."),
        ("age_set", "social_organization", "A cohort organized by socially recognized age or initiation whose members may share duties, identity and political roles."),
        ("shamanism", "religion", "A broad comparative label for practices in which specialists mediate with spirits through altered states, healing or ritual travel; local terms remain more precise."),
        ("pilgrimage", "religion", "Travel to a valued place that joins movement, devotion, memory, identity, economy and encounter."),
        ("diaspora", "mobility", "A dispersed population sustaining changing relations to multiple homes, histories and political contexts."),
        ("creolization", "cultural_change", "The formation of new languages and cultural forms through unequal contact, recombination and local innovation."),
        ("syncretism", "cultural_change", "The selective combination and reinterpretation of religious or cultural forms, often under conditions of contact and power imbalance."),
    ]
    facts = [
        "expert(cultural_anthropology).",
        "expert_domain(cultural_anthropology, anthropology).",
        f"expert_description(cultural_anthropology, {quote('fieldwork, cultural practices, social organization and comparative concepts')}).",
    ]
    for thinker, school, concept, desc in thinkers:
        facts.extend((
            f"anthropologist({thinker}).",
            f"anthropological_school({thinker}, {school}).",
            f"anthropological_concept({thinker}, {concept}).",
            f"humanities_topic({thinker}).",
            f"means({thinker}, {quote(desc)}).",
        ))
    for concept, domain, desc in concepts:
        facts.extend((
            f"anthropology_concept({concept}, {domain}).",
            f"humanities_topic({concept}).",
            f"means({concept}, {quote(desc)}).",
        ))
    rules = [
        "anthropology_topic($Topic) :- anthropology_concept($Topic, $Domain).",
        "concept_in_domain($Concept, $Domain) :- anthropology_concept($Concept, $Domain).",
        "anthropologist_studies($Thinker, $Concept) :- anthropological_concept($Thinker, $Concept).",
        "shares_anthropological_school($A, $B) :- anthropological_school($A, $School), anthropological_school($B, $School), dif($A, $B).",
        "exchange_institution($Concept) :- anthropology_concept($Concept, exchange).",
        "exchange_institution($Concept) :- anthropology_concept($Concept, ceremonial_exchange).",
        "mobility_practice($Concept) :- anthropology_concept($Concept, mobility).",
        "religious_practice($Concept) :- anthropology_concept($Concept, religion).",
        "subsistence_practice($Concept) :- anthropology_concept($Concept, subsistence).",
    ]
    emit("kb/experts/anthropology/cultural_anthropology.p0", "cultural anthropology", facts, rules)


def art_history() -> None:
    rows = [
        ("standard_of_ur", "unknown_sumerian_artists", "sumerian", "inlaid_object", "mesopotamia", "war_and_peace", "A richly inlaid object whose two main panels organize scenes of warfare, captives, labor and elite feasting."),
        ("bust_of_nefertiti", "thutmose_workshop", "amarna", "painted_sculpture", "egypt", "royal_image", "A painted limestone portrait associated with the Amarna court and the workshop of the sculptor Thutmose."),
        ("parthenon", "iktinos_and_kallikrates", "classical_greek", "temple_architecture", "athens", "civic_religion", "A temple of Athena whose architecture and sculpture joined civic identity, imperial resources and religious practice."),
        ("terracotta_army", "qin_workshops", "qin", "funerary_sculpture", "china", "imperial_afterlife", "Thousands of modeled figures formed part of the funerary complex of the first Qin emperor."),
        ("ajanta_caves", "multiple_indian_workshops", "buddhist", "rock_cut_complex", "india", "buddhist_narrative", "Rock-cut monasteries and shrines preserve sculpture and paintings that visualize Buddhist stories, devotion and courtly life."),
        ("sutton_hoo_helmet", "unknown_anglo_saxon_maker", "anglo_saxon", "metalwork", "england", "warrior_kingship", "An elaborate helmet from a ship burial combining protection, animal ornament and elite political symbolism."),
        ("great_mosque_of_cordoba", "umayyad_and_later_workshops", "islamic_iberian", "mosque_architecture", "cordoba", "sacred_space", "A mosque complex known for layered expansions, striped arches and the later insertion of a cathedral."),
        ("bayeux_tapestry", "unknown_norman_english_workshops", "romanesque", "embroidery", "norman_england", "conquest", "An embroidered narrative of the events surrounding the Norman conquest, shaped by sequence, inscription and political viewpoint."),
        ("angkor_wat", "khmer_workshops", "khmer", "temple_complex", "cambodia", "cosmic_kingship", "A monumental temple complex whose architecture and reliefs connect kingship, Hindu cosmology and later Buddhist use."),
        ("giotto_arena_chapel", "giotto", "proto_renaissance", "fresco_cycle", "padua", "sacred_narrative", "A fresco cycle using spatial clarity, gesture and emotion to make Christian narrative unfold across an architectural interior."),
        ("arnolfini_portrait", "jan_van_eyck", "northern_renaissance", "oil_painting", "bruges", "status_and_marriage", "A meticulous domestic portrait whose objects, reflected space and inscriptions have generated competing interpretations."),
        ("birth_of_venus", "sandro_botticelli", "italian_renaissance", "tempera_painting", "florence", "classical_myth", "A mythological image of Venus arriving at shore, joining classical revival, courtly poetry and linear grace."),
        ("last_supper", "leonardo_da_vinci", "italian_renaissance", "mural", "milan", "betrayal", "Leonardo organizes the apostles' reactions to Christ's announcement of betrayal through gesture, grouping and perspective."),
        ("sistine_ceiling", "michelangelo", "high_renaissance", "fresco_cycle", "rome", "creation", "A monumental ceiling program joining Genesis scenes, prophets, sibyls and complex bodies within painted architecture."),
        ("school_of_athens", "raphael", "high_renaissance", "fresco", "rome", "philosophy", "An idealized gathering of ancient thinkers staged through balanced groups and monumental perspective."),
        ("las_meninas", "diego_velazquez", "spanish_baroque", "oil_painting", "madrid", "representation", "A court painting that complicates who sees, who is depicted and where sovereign, artist and viewer stand."),
        ("girl_with_a_pearl_earring", "johannes_vermeer", "dutch_golden_age", "oil_painting", "delft", "gaze", "A tronie rather than a conventional portrait, using light, turn and an imagined costume to create immediacy."),
        ("plum_park_in_kameido", "utagawa_hiroshige", "ukiyo_e", "woodblock_print", "edo", "seasonal_landscape", "A dramatically cropped view of flowering plum trees that influenced later European experiments with composition."),
        ("third_of_may_1808", "francisco_goya", "romantic", "oil_painting", "madrid", "political_violence", "A stark image of execution that contrasts individualized victims with an impersonal firing squad."),
        ("liberty_leading_the_people", "eugene_delacroix", "romantic", "oil_painting", "paris", "revolution", "An allegorical yet bodily image of the July Revolution combining social types, casualties and a flag-bearing Liberty."),
        ("olympia", "edouard_manet", "modernist", "oil_painting", "paris", "gaze_and_class", "A confrontational modern nude whose direct gaze and social details challenged academic conventions."),
        ("impression_sunrise", "claude_monet", "impressionist", "oil_painting", "le_havre", "modern_perception", "A harbor scene of changing light whose title helped name Impressionism."),
        ("starry_night", "vincent_van_gogh", "post_impressionist", "oil_painting", "saint_remy", "night_landscape", "A remembered and transformed night view in which rhythmic brushwork unifies sky, village and cypress."),
        ("the_scream", "edvard_munch", "symbolist", "painting", "norway", "anxiety", "A figure and landscape bend into an image of overwhelming anxiety and modern alienation."),
        ("les_demoiselles_davignon", "pablo_picasso", "early_cubist", "oil_painting", "paris", "fragmented_space", "A disruptive group figure composition that fractures bodies and space while raising difficult questions about primitivism and the colonial gaze."),
        ("black_square", "kazimir_malevich", "suprematist", "painting", "russia", "abstraction", "A radically reduced geometric image presented as a new beginning for nonobjective art."),
        ("fountain", "marcel_duchamp", "dada", "readymade", "new_york", "artistic_authority", "A manufactured urinal submitted as art, shifting attention from craft to selection, institution and naming."),
        ("migration_series", "jacob_lawrence", "american_modern", "painting_series", "united_states", "great_migration", "A sixty-panel sequence narrating the Great Migration through compressed shapes, recurring colors and concise captions."),
        ("guernica", "pablo_picasso", "modernist", "mural_painting", "spain", "war_trauma", "A monumental monochrome response to the bombing of Guernica, using fractured bodies and symbols rather than documentary perspective."),
        ("infinity_mirror_rooms", "yayoi_kusama", "contemporary", "installation", "japan_and_global", "repetition", "Immersive mirrored installations multiply lights, objects and viewers into environments of repetition and unstable scale."),
    ]
    facts = [
        "expert(art_history).",
        "expert_domain(art_history, visual_arts).",
        f"expert_description(art_history, {quote('artworks, makers, movements, media, places and interpretive themes')}).",
    ]
    for work, artist, movement, medium, place, theme, desc in rows:
        facts.extend((
            f"artwork({work}, {artist}, {movement}, {medium}).",
            f"artist_of({artist}, {work}).",
            f"artwork_place({work}, {place}).",
            f"artwork_theme({work}, {theme}).",
            f"humanities_topic({work}).",
            f"means({work}, {quote(desc)}).",
        ))
    rules = [
        "visual_artwork($Work) :- artwork($Work, $Artist, $Movement, $Medium).",
        "artwork_by($Work, $Artist) :- artist_of($Artist, $Work).",
        "artist_in_movement($Artist, $Movement) :- artwork($Work, $Artist, $Movement, $Medium).",
        "shares_art_movement($A, $B) :- artwork($A, $ArtistA, $Movement, $MediumA), artwork($B, $ArtistB, $Movement, $MediumB), dif($A, $B).",
        "shares_art_medium($A, $B) :- artwork($A, $ArtistA, $MovementA, $Medium), artwork($B, $ArtistB, $MovementB, $Medium), dif($A, $B).",
        "art_theme_in_work($Theme, $Work) :- artwork_theme($Work, $Theme).",
    ]
    emit("kb/experts/arts/art_history.p0", "global art history", facts, rules)


def civilizations() -> None:
    rows = [
        ("sumer", "mesopotamia", "bronze_age", "city_state", "cuneiform", "Sumerian cities developed temple and palace institutions, cuneiform administration and influential literary traditions."),
        ("akkadian_empire", "mesopotamia", "bronze_age", "territorial_empire", "imperial_administration", "The Akkadian Empire linked multiple Mesopotamian cities under a royal ideology and wider administrative network."),
        ("old_kingdom_egypt", "nile_valley", "bronze_age", "divine_kingship", "pyramid_complexes", "Old Kingdom Egypt coordinated agriculture, taxation, craft labor and royal mortuary building along the Nile."),
        ("indus_civilization", "south_asia", "bronze_age", "urban_network", "planned_cities", "Indus cities shared weights, craft systems, drainage and urban forms across a wide trade network."),
        ("shang_china", "yellow_river", "bronze_age", "royal_lineage", "oracle_bone_writing", "Shang centers joined bronze production, warfare, lineage ritual and early Chinese writing."),
        ("zhou_china", "east_asia", "iron_age", "feudal_order", "mandate_of_heaven", "Zhou political thought used the Mandate of Heaven to explain legitimate rule and dynastic change."),
        ("achaemenid_empire", "west_and_central_asia", "classical", "satrapal_empire", "royal_road", "The Achaemenid Empire governed diverse regions through satrapies, tribute, roads and flexible local arrangements."),
        ("classical_athens", "mediterranean", "classical", "citizen_polis", "direct_democracy", "Athens developed participatory institutions for male citizens while depending on empire, slavery and excluded populations."),
        ("roman_republic", "mediterranean", "classical", "republic", "mixed_constitution", "The Roman Republic combined assemblies, magistracies and senate authority while conquest intensified inequality and military competition."),
        ("roman_empire", "mediterranean", "classical", "imperial_state", "provincial_network", "Rome connected provinces through law, taxation, armies, cities, roads and unequal forms of citizenship."),
        ("maurya_empire", "south_asia", "classical", "imperial_state", "ashokan_edicts", "The Maurya Empire coordinated a large South Asian realm; Ashoka's inscriptions publicized ethical and administrative ideals."),
        ("gupta_india", "south_asia", "late_antiquity", "regional_empire", "classical_sanskrit_culture", "Gupta-period courts supported Sanskrit learning, religious institutions, mathematics and regional political networks."),
        ("han_china", "east_asia", "classical", "bureaucratic_empire", "civil_service", "The Han state expanded imperial administration, historical writing, frontier systems and long-distance exchange."),
        ("aksum", "horn_of_africa", "late_antiquity", "trading_kingdom", "coinage_and_red_sea_trade", "Aksum linked African highlands and Red Sea commerce, minted coins and adopted Christianity."),
        ("byzantine_empire", "eastern_mediterranean", "medieval", "imperial_state", "roman_law_and_orthodoxy", "The Byzantine Empire sustained Roman institutions in Greek-speaking forms while shaping Orthodox Christianity and regional diplomacy."),
        ("abbasid_caliphate", "west_asia", "medieval", "caliphal_empire", "translation_and_scholarship", "Abbasid cities supported commerce, administration and multilingual scholarship across Islamic intellectual networks."),
        ("ghana_empire", "west_africa", "medieval", "trading_state", "gold_salt_exchange", "The Ghana Empire drew power from regional agriculture, political authority and taxation of trans-Saharan exchange."),
        ("mali_empire", "west_africa", "medieval", "imperial_network", "mande_trade_and_scholarship", "Mali connected Mande political institutions, goldfields, trade routes and centers of Islamic learning."),
        ("songhai_empire", "west_africa", "early_modern", "riverine_empire", "niger_trade", "Songhai controlled major Niger River cities and trade routes through provincial administration and military power."),
        ("swahili_city_states", "east_african_coast", "medieval", "urban_trade_network", "indian_ocean_exchange", "Swahili towns joined African languages and societies with Indian Ocean commerce, Islam and cosmopolitan urban culture."),
        ("khmer_empire", "southeast_asia", "medieval", "temple_state", "hydraulic_landscape", "Khmer rulers built monumental temple landscapes within a densely managed agrarian and hydraulic region."),
        ("majapahit", "maritime_southeast_asia", "medieval", "maritime_kingdom", "archipelagic_trade", "Majapahit projected courtly authority through alliances, ports and trade across parts of the Indonesian archipelago."),
        ("heian_japan", "japan", "medieval", "court_state", "kana_literature", "Heian court culture developed aristocratic institutions, Buddhist networks and major writing in kana."),
        ("mongol_empire", "eurasia", "medieval", "steppe_empire", "relay_network", "The Mongol Empire combined mobile military organization with protected routes, tribute and exchange across Eurasia."),
        ("aztec_triple_alliance", "mesoamerica", "late_postclassic", "tributary_empire", "chinampa_agriculture", "The Triple Alliance centered on Tenochtitlan and drew tribute from conquered polities within a dense Mesoamerican world."),
        ("inca_empire", "andes", "late_precolumbian", "road_empire", "labor_tax", "The Inca state coordinated Andean regions through roads, storehouses, resettlement and rotating labor obligations."),
        ("ottoman_empire", "mediterranean_and_west_asia", "early_modern", "imperial_state", "provincial_pluralism", "The Ottoman Empire governed diverse provinces through court, military, fiscal and religious institutions that changed over centuries."),
        ("mughal_empire", "south_asia", "early_modern", "imperial_state", "mansabdari", "Mughal rule linked military ranks, revenue administration, regional elites and a cosmopolitan court culture."),
        ("ming_china", "east_asia", "early_modern", "bureaucratic_empire", "maritime_and_inland_exchange", "Ming China combined examination government, commercial expansion, print culture and shifting maritime policies."),
        ("haudenosaunee_confederacy", "northeastern_north_america", "precolonial_and_modern", "confederacy", "great_law_of_peace", "The Haudenosaunee Confederacy joins distinct nations through councils, clan relations and the Great Law of Peace."),
    ]
    facts = [
        "expert(world_civilizations).",
        "expert_domain(world_civilizations, history).",
        f"expert_description(world_civilizations, {quote('comparative institutions, regions, periods and innovations in world history')}).",
    ]
    for polity, region, period, institution, innovation, desc in rows:
        facts.extend((
            f"historical_polity({polity}, {region}, {period}, {institution}).",
            f"historical_innovation({polity}, {innovation}).",
            f"historical_region({polity}, {region}).",
            f"historical_period({polity}, {period}).",
            f"humanities_topic({polity}).",
            f"means({polity}, {quote(desc)}).",
        ))
    rules = [
        "civilization_topic($Polity) :- historical_polity($Polity, $Region, $Period, $Institution).",
        "polity_in_region($Polity, $Region) :- historical_region($Polity, $Region).",
        "polity_in_period($Polity, $Period) :- historical_period($Polity, $Period).",
        "shares_historical_region($A, $B) :- historical_region($A, $Region), historical_region($B, $Region), dif($A, $B).",
        "shares_historical_period($A, $B) :- historical_period($A, $Period), historical_period($B, $Period), dif($A, $B).",
        "historical_institution($Polity, $Institution) :- historical_polity($Polity, $Region, $Period, $Institution).",
        "historical_contribution($Polity, $Innovation) :- historical_innovation($Polity, $Innovation).",
    ]
    emit("kb/experts/history/civilizations.p0", "world civilizations", facts, rules)


def main() -> None:
    literature()
    philosophy()
    anthropology()
    art_history()
    civilizations()


if __name__ == "__main__":
    main()
