/* gen321 (forge-master-plan §15 row 7): the ONLY translation unit that sees the
 * build stamp. It is deliberately tiny — it is recompiled on every commit, and
 * nothing else should be.
 *
 * obj/version_stamp.h is generated by the Makefile from the VERSION file (the
 * single source of the generation label) and `git rev-parse --short HEAD`. It
 * lives in the build directory, not in src/, because it is a build artifact:
 * putting it under src/ is what dragged it into every object's header closure.
 */
#include "version_stamp.h"   /* generated into the build dir (-Iobj) */
#include "version.h"

const char *parrot0_version(void) {
    return PARROT0_GEN "@" PARROT0_COMMIT;
}
